# S = input("Enter String : ")
S = "Clement"

print(S.center(10))
print(S.count('e'))
print(S.count('e',0,3))
print(S.endswith('ent'))
print(S.find('m'))
print(S.find('m',0,2))
print(S.isalpha())
print(S.isdigit())
print(S.join("__"))
print(S.lower())
print(S.replace('e', 'g',1))
print(S.split("e"))
print(S.startswith('Cle'))
print(S.strip("C"))
print(S.upper())
print(S.capitalize())
print(S.casefold())
print(S.encode())